### ISSUE TITLE
Found more than one matching milestone?!

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/neptune#93] opened 2017-08-31 08:45 UTC
Releasing swarm v3.3.5, I just got this error:
```
swarm-tsunami:v3.3.x *$ ../neptune/build/devel/bin/neptune-release 
We are on branch v3.3.x
Detected release v3.3.5
Actions to be done:
 * Creating annotated tag v3.3.5 (git tag -F- v3.3.5 v3.3.x)
 * Checkout v3.x.x locally (git checkout v3.x.x)
 * Merge v3.3.5 into v3.x.x (git merge -m "Merge tag v3.3.5 into v3.x.x" v3.3.5)
 * Checkout v4.2.x locally (git checkout v4.2.x)
 * Merge v3.3.5 into v4.2.x (git merge -m "Merge tag v3.3.5 into v4.2.x" v3.3.5)
 * Creating annotated tag v4.2.4 (git tag -F- v4.2.4 v4.2.x)
 * Checkout v4.x.x locally (git checkout v4.x.x)
 * Merge v4.2.4 into v4.x.x (git merge -m "Merge tag v4.2.4 into v4.x.x" v4.2.4)
 * Checkout original branch v3.3.x (git checkout v3.3.x)

Would you like to continue? y/n: y

Creating annotated tag v3.3.5 ...
	git tag -F- v3.3.5 v3.3.x
	
Checkout v3.x.x locally ...
	git checkout v3.x.x
	Switched to branch 'v3.x.x'
Your branch is up-to-date with 'upstream/v3.x.x'.
Merge v3.3.5 into v3.x.x ...
	git merge -m "Merge tag v3.3.5 into v3.x.x" v3.3.5
	Removing ci/travis.sh
Removing ci/travis-script.sh
Removing ci/travis-install.sh
Removing ci/travis-after-success.sh
Removing ci/ci.sh
Removing Dockerfile
Merge made by the 'recursive' strategy.
 .gitmodules                                      |  3 ++
 .travis.yml                                      | 28 +++++++++++++----
 Dockerfile                                       |  3 --
 beaver.Dockerfile                                |  1 +
 ci/ci.sh                                         | 33 --------------------
 ci/travis-after-success.sh                       |  4 ---
 ci/travis-install.sh                             |  5 ---
 ci/travis-script.sh                              |  5 ---
 ci/travis.sh                                     | 10 ------
 docker/build                                     |  3 +-
 src/swarm/neo/authentication/CredentialsFile.d   |  3 ++
 src/swarm/neo/connection/ConnectionBase.d        | 39 +++++++++++++++++++++++-
 src/swarm/neo/connection/YieldedRequestOnConns.d | 11 +++++--
 src/swarm/neo/node/Connection.d                  |  4 +--
 src/swarm/neo/node/RequestSet.d                  | 33 ++++++++++++--------
 src/swarm/neo/protocol/socket/MessageGenerator.d |  8 +++--
 submodules/beaver                                |  1 +
 17 files changed, 106 insertions(+), 88 deletions(-)
 delete mode 100644 Dockerfile
 create mode 100644 beaver.Dockerfile
 delete mode 100755 ci/ci.sh
 delete mode 100755 ci/travis-after-success.sh
 delete mode 100755 ci/travis-install.sh
 delete mode 100755 ci/travis-script.sh
 delete mode 100755 ci/travis.sh
 create mode 160000 submodules/beaver
Checkout v4.2.x locally ...
	git checkout v4.2.x
	Switched to branch 'v4.2.x'
M	submodules/ocean
Your branch is up-to-date with 'upstream/v4.2.x'.
Merge v3.3.5 into v4.2.x ...
	git merge -m "Merge tag v3.3.5 into v4.2.x" v3.3.5
	Auto-merging src/swarm/neo/protocol/socket/MessageGenerator.d
Auto-merging src/swarm/neo/node/RequestSet.d
Auto-merging src/swarm/neo/node/Connection.d
Auto-merging src/swarm/neo/connection/ConnectionBase.d
Auto-merging src/swarm/neo/authentication/CredentialsFile.d
Removing ci/travis.sh
Removing ci/travis-script.sh
Removing ci/travis-install.sh
Removing ci/travis-after-success.sh
Removing ci/ci.sh
Removing Dockerfile
Merge made by the 'recursive' strategy.
 .gitmodules                                      |  3 ++
 .travis.yml                                      | 28 +++++++++++++----
 Dockerfile                                       |  3 --
 beaver.Dockerfile                                |  1 +
 ci/ci.sh                                         | 33 --------------------
 ci/travis-after-success.sh                       |  4 ---
 ci/travis-install.sh                             |  5 ---
 ci/travis-script.sh                              |  5 ---
 ci/travis.sh                                     | 10 ------
 docker/build                                     |  3 +-
 src/swarm/neo/authentication/CredentialsFile.d   |  3 ++
 src/swarm/neo/connection/ConnectionBase.d        | 39 +++++++++++++++++++++++-
 src/swarm/neo/connection/YieldedRequestOnConns.d | 11 +++++--
 src/swarm/neo/node/Connection.d                  |  4 +--
 src/swarm/neo/node/RequestSet.d                  | 33 ++++++++++++--------
 src/swarm/neo/protocol/socket/MessageGenerator.d |  8 +++--
 submodules/beaver                                |  1 +
 17 files changed, 106 insertions(+), 88 deletions(-)
 delete mode 100644 Dockerfile
 create mode 100644 beaver.Dockerfile
 delete mode 100755 ci/ci.sh
 delete mode 100755 ci/travis-after-success.sh
 delete mode 100755 ci/travis-install.sh
 delete mode 100755 ci/travis-script.sh
 delete mode 100755 ci/travis.sh
 create mode 160000 submodules/beaver
Creating annotated tag v4.2.4 ...
	git tag -F- v4.2.4 v4.2.x
	
Checkout v4.x.x locally ...
	git checkout v4.x.x
	Switched to branch 'v4.x.x'
M	submodules/ocean
Your branch is up-to-date with 'upstream/v4.x.x'.
Merge v4.2.4 into v4.x.x ...
	git merge -m "Merge tag v4.2.4 into v4.x.x" v4.2.4
	Auto-merging test/neo/main.d
Auto-merging test/neo/client/request/Put.d
Auto-merging test/neo/client/Client.d
Auto-merging test/client_auth/main.d
Removing ci/travis.sh
Removing ci/travis-script.sh
Removing ci/travis-install.sh
Removing ci/travis-after-success.sh
Removing ci/ci.sh
Removing Dockerfile
Merge made by the 'recursive' strategy.
 .gitmodules                                        |  3 ++
 .travis.yml                                        | 28 ++++++++++++----
 Dockerfile                                         |  3 --
 beaver.Dockerfile                                  |  1 +
 ci/ci.sh                                           | 33 ------------------
 ci/travis-after-success.sh                         |  4 ---
 ci/travis-install.sh                               |  5 ---
 ci/travis-script.sh                                |  5 ---
 ci/travis.sh                                       | 10 ------
 docker/build                                       |  3 +-
 src/swarm/neo/AddrPort.d                           |  2 +-
 src/swarm/neo/authentication/ClientCredentials.d   |  2 +-
 src/swarm/neo/authentication/CredentialsFile.d     |  3 ++
 src/swarm/neo/authentication/NodeCredentials.d     |  2 +-
 src/swarm/neo/client/mixins/AllNodesRequestCore.d  |  2 +-
 .../neo/client/mixins/SuspendableRequestCore.d     |  2 +-
 .../neo/client/requests/NotificationFormatter.d    |  2 +-
 src/swarm/neo/connection/ConnectionBase.d          | 39 +++++++++++++++++++++-
 src/swarm/neo/connection/YieldedRequestOnConns.d   | 11 ++++--
 src/swarm/neo/node/Connection.d                    |  4 +--
 src/swarm/neo/node/RequestSet.d                    | 33 +++++++++++-------
 src/swarm/neo/protocol/socket/MessageGenerator.d   |  8 +++--
 src/swarm/neo/request/RequestEventDispatcher.d     |  2 +-
 src/swarm/neo/util/DelayedSuspender.d              |  2 +-
 src/swarm/neo/util/Formatter.d                     |  2 +-
 submodules/beaver                                  |  1 +
 test/client_auth/main.d                            |  2 +-
 test/neo/client/Client.d                           |  2 +-
 test/neo/client/NotifierTypes.d                    |  2 +-
 test/neo/client/request/Get.d                      |  2 +-
 test/neo/client/request/GetAll.d                   |  2 +-
 test/neo/client/request/Put.d                      |  2 +-
 test/neo/client/request/internal/Get.d             |  2 +-
 test/neo/client/request/internal/GetAll.d          |  2 +-
 test/neo/client/request/internal/Put.d             |  2 +-
 test/neo/common/Get.d                              |  2 +-
 test/neo/common/GetAll.d                           |  2 +-
 test/neo/common/Put.d                              |  2 +-
 test/neo/common/RequestCodes.d                     |  2 +-
 test/neo/main.d                                    |  2 +-
 test/neo/node/Node.d                               |  2 +-
 test/neo/node/Storage.d                            |  2 +-
 test/neo/node/request/Get.d                        |  2 +-
 test/neo/node/request/GetAll.d                     |  2 +-
 test/neo/node/request/Put.d                        |  2 +-
 45 files changed, 134 insertions(+), 116 deletions(-)
 delete mode 100644 Dockerfile
 create mode 100644 beaver.Dockerfile
 delete mode 100755 ci/ci.sh
 delete mode 100755 ci/travis-after-success.sh
 delete mode 100755 ci/travis-install.sh
 delete mode 100755 ci/travis-script.sh
 delete mode 100755 ci/travis.sh
 create mode 160000 submodules/beaver
Checkout original branch v3.3.x ...
	git checkout v3.3.x
	Switched to branch 'v3.3.x'
Done! Some references should be pushed: ["v3.3.5", "v3.x.x", "v4.2.4", "v4.2.x", "v4.x.x"]
Would you like to push the modified references now? y/n: y
Some tags on github should be released: ["v3.3.5", "v4.2.4"]
Would you like to release those tags now? y/n: y
Creating v3.3.5 ... failed: Reading from TLS stream was unsuccessful with ret 0
retrying ...
Creating v3.3.5 ... failed: Found more than one matching milestone?!
retrying ...
Creating v3.3.5 ... failed: Found more than one matching milestone?!
retrying ...
Creating v3.3.5 ... failed: Found more than one matching milestone?!
retrying ...
Creating v3.3.5 ... failed: Found more than one matching milestone?!
retrying ...
Creating v3.3.5 ... failed: Found more than one matching milestone?!
retrying ...
Creating v3.3.5 ... failed: Found more than one matching milestone?!
retrying ...
Creating v3.3.5 ... failed: Found more than one matching milestone?!
retrying ...
Creating v3.3.5 ... failed: Found more than one matching milestone?!
retrying ...
Creating v3.3.5 ... failed: Found more than one matching milestone?!
Giving up after 10 attempts
object.Exception@/home/gavinnorman/devel/neptune/src/release/main.d(220): Found more than one matching milestone?!
----------------
/usr/include/dmd/phobos/std/exception.d:420 pure @safe void std.exception.bailOut!(Exception).bailOut(immutable(char)[], ulong, const(char[])) [0x869ed6]
/usr/include/dmd/phobos/std/exception.d:388 pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x86a07e]
/home/gavinnorman/devel/neptune/src/release/main.d:220 void release.main.createGithubRelease(octod.core.HTTPConnection, octod.api.repos.Repository, immutable(char)[], immutable(char)[]) [0x76cc76]
/home/gavinnorman/devel/neptune/src/release/main.d:159 void release.main.main(immutable(char)[][]).__lambda5() [0x76cb26]
./src/release/shellHelper.d:240 void release.shellHelper.__T10keepTryingS193std5stdio8writeflnZ.keepTrying(void delegate(), int, core.time.Duration) [0x783d2f]
/home/gavinnorman/devel/neptune/src/release/main.d:156 _Dmain [0x76c7f9]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFNlZv [0x924dff]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x924d2f]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x924da8]
??:? scope void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x924d2f]
??:? _d_run_main [0x924c9f]
??:? main [0x773ba5]
??:? __libc_start_main [0x26e0b82f]
```
Obviously, there's only one `v3.3.5` milestone in swarm (https://github.com/sociomantic-tsunami/swarm/milestone/22).

**Comment by mathias-baumann-sociomantic** [comment] 2017-09-11 12:17
Might there have been a draft-release of the same name?

**Comment by mihails-strasuns-sociomantic** [comment] 2017-09-11 12:18
Nope. I get it with ocean every single time when trying to make release btw.

**Comment by mathias-baumann-sociomantic** [comment] 2017-09-11 12:23
Closing as a dup. of https://github.com/sociomantic-tsunami/neptune/issues/82

**Closed by mathias-baumann-sociomantic** 2017-09-11 12:23 UTC
Labels: part-release-tool, type-bug

**Comment by leandro-lucarella-sociomantic** [comment] 2017-09-12 09:38
Duplicate of #82

**Comment by leandro-lucarella-sociomantic** [comment] 2017-09-12 09:38
(GitHub is really picky with the "duplicate of" keyword)
