### ISSUE TITLE
GitHub release text for patch release should contain notes too (?)

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/neptune#103] opened 2017-09-22 16:49 UTC
Right now the _e-mail_ notes for a patch release contain a list of issues solved in that release, for example:

```md
Issues fixed in this release:

v0.2.2
======

* gen-dockerfile: Fix docker repository and tag parsing #29
* editorconfig: Fix indent for Makefiles #27
* Mention wildcard support in the readme #26

http://github.com/sociomantic-tsunami/beaver/releases/tag/v0.2.2
```

But then the release _in github_ only has a link to the milestone, which is a bit inconvenient as to see a list of issues fixed you have an extra indirection (also release notes will hardly accidentally change, while milestones are live and someone could accidentally move some issue to/from the milestone). It should be free to include the list of issues fixes in the notes too (we can keep the link to the milestone).

Also the milestone link should point to the closed issues (append `?closed=1` to the end of the link), not the open ones (which should be empty).

**Comment by nemanja-boric-sociomantic** [comment] 2017-10-02 09:58
Traditionally, we don't have release notes for the patch releases. Maybe we should add a new category `*.bugfix.md` inside `relnotes`, for the patch releases that need this?

**Comment by mathias-baumann-sociomantic** [comment] 2017-10-10 11:49
>  It should be free to include the list of issues fixes in the notes too (we can keep the link to the milestone).

But... it is including that list.. even in your example.. I am confused what you want

**Comment by mathias-baumann-sociomantic** [comment] 2017-10-10 11:50
Ah you mean the github-notes and tag notes. I see.

**Comment by mihails-strasuns-sociomantic** [comment] 2017-10-10 11:50
"release notes" == "github release text"

**Comment by mihails-strasuns-sociomantic** [comment] 2017-10-10 11:51
btw for mail announcements using full issue links instead of just numbers would probably be more convenient

**Comment by leandro-lucarella-sociomantic** [comment] 2017-10-10 16:17
> Traditionally, we don't have release notes for the patch releases. Maybe we should add a new category *.bugfix.md inside relnotes, for the patch releases that need this?

I think it should be gotten from the issues in the milestones, this is what I did in my release script and I think it makes sense. This is already being generated for the e-mail IIRC. I don't think we should have manually-written notes for every bug fix.

**Comment by mathias-lang-sociomantic** [comment] 2018-02-23 11:12
> But then the release in github only has a link to the milestone

As far as I can see, there's not evenj a link to the milestone anymore.

**Comment by mathias-baumann-sociomantic** [comment] 2018-02-27 16:17
Closing as duplicate of https://github.com/sociomantic-tsunami/neptune/issues/57

**Closed by mathias-baumann-sociomantic** 2018-02-27 16:17 UTC
Labels: part-tool-release, type-enhancement
